# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
name = "Accueil"
url = "#hero"
weight = 10

[[main]]
name = "Parcours"
url = "#experience"
weight = 20

[[main]]
name = "Compétences"
url = "#skills"
weight = 30

[[main]]
name = "Réalisations"
url = "#projects"
weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
name = "Mon CV"
url = "files/cv.pdf"
weight = 50


[[main]]
name = "Contact"
url = "#contact"
weight = 60

